# GENERATED by bin/generate-shell-config — DO NOT EDIT.
# Edit shell/*.spec and re-run `just generate` (or bin/generate-shell-config).
#
# Source: shell/path.spec

# Built once from an ordered list rather than accumulated with
# `set -x PATH $PATH ...`, which appended unconditionally and left 15
# duplicated entries in a nested fish shell.
#
# fish_add_path is deliberately not used: without --path it writes
# $fish_user_paths, a *universal* variable that persists across sessions and
# survives every change to this file.

set -l __dl_want

set -a __dl_want $HOME/.local/share/mise/shims
set -a __dl_want $HOME/.dotfiles/bin
set -a __dl_want $HOME/.dotfiles/private/bin
if test -n "$__dl_brew_prefix"
    set -a __dl_want $__dl_brew_prefix/bin
    set -a __dl_want $__dl_brew_prefix/sbin
    set -a __dl_want $__dl_brew_prefix/whalebrew/bin
end
set -a __dl_want $HOME/.local/pi-agent-npm/bin
set -a __dl_want $HOME/.grok/bin
set -a __dl_want $HOME/.opencode/bin
set -a __dl_want $HOME/.bun/bin
set -a __dl_want $HOME/.local/share/pnpm/bin
set -a __dl_want $HOME/.cargo/bin
set -a __dl_want $HOME/.volta/bin
set -a __dl_want $HOME/.config/emacs/bin
set -a __dl_want $HOME/.lmstudio/bin
set -a __dl_want $HOME/.local/bin
set -a __dl_want /usr/local/sbin
set -a __dl_want /usr/local/bin
set -a __dl_want $HOME/.tmux/plugins/tmux-nvr/bin
set -a __dl_want $HOME/.tmux/plugins/t-smart-tmux-session-manager/bin
if test "$__dl_os" = Darwin
    set -a __dl_want /Applications/Obsidian.app/Contents/MacOS
end
set -a __dl_want /usr/bin
set -a __dl_want /bin
set -a __dl_want /usr/sbin
set -a __dl_want /sbin

set -l __dl_new
for __dl_p in $__dl_want
    if test -d $__dl_p; and not contains -- $__dl_p $__dl_new
        set -a __dl_new $__dl_p
    end
end

# Inherited entries keep their order and are not existence-filtered.
for __dl_p in $PATH
    if not contains -- $__dl_p $__dl_new
        set -a __dl_new $__dl_p
    end
end

set -gx PATH $__dl_new
