# GENERATED by bin/generate-shell-config — DO NOT EDIT.
# Edit shell/*.spec and re-run `just generate` (or bin/generate-shell-config).
#
# Source: shell/env.spec, shell/path.spec
#
# Nushell gets PATH and the unguarded environment from the same spec as the
# other three shells. Guarded entries are skipped rather than translated: the
# `path exists` filter below already handles the platform-specific PATH
# entries, and nushell cannot conditionally assign $env from inside a block.

let __dl_brew_prefix = (
    if ("/opt/homebrew/bin/brew" | path exists) { "/opt/homebrew" }
    else if ("/usr/local/bin/brew" | path exists) { "/usr/local" }
    else if ("/home/linuxbrew/.linuxbrew/bin/brew" | path exists) { "/home/linuxbrew/.linuxbrew" }
    else { "" }
)

$env.KEYTIMEOUT = $"1"
$env.EDITOR = $"nvim"
$env.GIT_EDITOR = $"nvim"
$env.XDG_CACHE_HOME = $"($env.HOME)/.cache"
$env.XDG_CONFIG_HOME = $"($env.HOME)/.config"
$env.XDG_DATA_HOME = $"($env.HOME)/.local/share"
$env.XDG_STATE_HOME = $"($env.HOME)/.local/state"
$env.FZF_ALT_C_COMMAND = $"fd --type d --follow --exclude .git --exclude node_modules --color=never --hidden"
$env.FZF_ALT_C_OPTS = $"--preview 'tree -C {} | head -50'"
$env.FZF_CTRL_R_OPTS = $"--reverse"
$env.FZF_CTRL_T_COMMAND = $"git ls-files --cached --others --exclude-standard | fd --hidden --type f --type l --follow --exclude .git --exclude node_modules"
$env.FZF_CTRL_T_OPTS = $"--preview 'bat --color=always --style=numbers {}' --bind shift-up:preview-page-up,shift-down:preview-page-down"
$env.FZF_DEFAULT_COMMAND = $"git ls-files --cached --others --exclude-standard | fd --hidden --type f --type l --follow --exclude .git --exclude node_modules"
$env.FZF_DEFAULT_OPTS = $"--no-height"
$env.FZF_TMUX = $"1"
$env.FZF_TMUX_OPTS = $"-p"
$env.VOLTA_HOME = $"($env.HOME)/.volta"
$env.BUN_INSTALL = $"($env.HOME)/.bun"
$env.PNPM_HOME = $"($env.HOME)/.local/share/pnpm"

$env.PATH = ([
    $"($env.HOME)/.local/share/mise/shims"
    $"($env.HOME)/.dotfiles/bin"
    $"($env.HOME)/.dotfiles/private/bin"
    $"($__dl_brew_prefix)/bin"
    $"($__dl_brew_prefix)/sbin"
    $"($__dl_brew_prefix)/whalebrew/bin"
    $"($env.HOME)/.local/pi-agent-npm/bin"
    $"($env.HOME)/.grok/bin"
    $"($env.HOME)/.opencode/bin"
    $"($env.HOME)/.bun/bin"
    $"($env.HOME)/.local/share/pnpm/bin"
    $"($env.HOME)/.cargo/bin"
    $"($env.HOME)/.volta/bin"
    $"($env.HOME)/.config/emacs/bin"
    $"($env.HOME)/.lmstudio/bin"
    $"($env.HOME)/.local/bin"
    $"/usr/local/sbin"
    $"/usr/local/bin"
    $"($env.HOME)/.tmux/plugins/tmux-nvr/bin"
    $"($env.HOME)/.tmux/plugins/t-smart-tmux-session-manager/bin"
    $"/Applications/Obsidian.app/Contents/MacOS"
    $"/usr/bin"
    $"/bin"
    $"/usr/sbin"
    $"/sbin"
] | where { |p| $p | path exists } | append $env.PATH | uniq)
