- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.ack: ack
    ~/.ag: ag
    ~/.ctags: ctags
    ~/.wget: wget
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
