- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/.ack: ack
    ~/.ag: ag
    ~/.config/alacritty: alacritty
    ~/.config/base16-shell: .base16-shell
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship.toml
    ~/.config/tmuxinator: tmuxinator
    ~/.ctags: ctags
    ~/.editorconfig: editorconfig
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.hammerspoon: hammerspoon
    ~/.pandoc: pandoc
    ~/.ripgreprc: ripgrep
    ~/.tmux.conf: tmux.conf
    ~/.vale.ini: vale.ini
    ~/.vale: .vale
    ~/.wget: wget
    ~/.zshrc: zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
    - [nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync', Installing Neovim Packer plugins]
    - [nvim +Mason +15sleep +qall, Installing Neovim Mason plugins]
