- defaults:
    link:
      relink: true

- clean: ["~"]

- create:
    - ~/.config/gh
    - ~/.config/gh-dash
    - ~/.config/tmux

- link:
    ~/.config/base16-shell: .base16-shell
    ~/.config/fish: fish
    ~/.config/gh-dash/config.yml: github/gh-dash/config.yml
    ~/.config/gh/config.yml: github/gh/config.yml
    ~/.config/nvim: nvim
    ~/.config/oatmeal: oatmeal
    ~/.config/ranger: ranger
    ~/.config/sesh: sesh
    ~/.config/sketchybar: sketchybar
    ~/.config/starship.toml: prompt/starship.toml
    ~/.config/superfile: superfile
    ~/.config/tmux/tmux-nerd-font-window-name.yml: tmux/tmux-nerd-font-window-name.yml
    ~/.config/zed/settings.json: zed/settings.json
    ~/.curlrc: url/curlrc
    ~/.editorconfig: style/editorconfig
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.gitmux.conf: tmux/gitmux.conf
    ~/.tmux-cht-command: tmux/tmux-cht-command
    ~/.tmux-cht-languages: tmux/tmux-cht-languages
    ~/.tmux.conf: tmux/tmux.conf
    ~/.wezterm.lua: wezterm/wezterm.lua
    ~/.wget: url/wget
    ~/.zsh.d: zsh/zsh.d
    ~/.zshrc: zsh/zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [
        ~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1,
        Installing tmux plugins,
      ]
