- defaults:
    link:
      relink: true

- clean: ["~"]

- link:
    ~/.ack: ack
    ~/.ag: ag
    ~/.asdfrc: asdf/asdfrc
    ~/.config/base16-shell: .base16-shell
    ~/.config/gh/config.yml: github/config.yml
    ~/.config/karabiner: karabiner
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship.toml
    ~/.config/svim: svim
    ~/.config/tmuxinator: tmuxinator
    ~/.ctags: ctags
    ~/.default-gems: asdf/default-gems
    ~/.default-npm-packages: asdf/default-npm-packages
    ~/.default-python-packages: asdf/default-python-packages
    ~/.editorconfig: editorconfig
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.hammerspoon: hammerspoon
    ~/.pandoc: pandoc
    ~/.ripgreprc: ripgrep
    ~/.tmux-cht-command: tmux/tmux-cht-command
    ~/.tmux-cht-languages: tmux/tmux-cht-languages
    ~/.tmux.conf: tmux.conf
    ~/.vale.ini: vale.ini
    ~/.vale: .vale
    ~/.wget: wget
    ~/.zsh.d: zsh
    ~/.zshrc: zshrc
    ~/Library/Application Support/lazygit/config.yml: lazygit.yml

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [
        ~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1,
        Installing tmux plugins,
      ]
