- defaults:
    link:
      relink: true

- clean: ["~"]

- create:
    - ~/.config/lazygit
    - ~/.config/lazydocker

- link:
    ~/.ack: search/ack
    ~/.ag: search/ag
    ~/.asdfrc: asdf/asdfrc
    ~/.config/alacritty: alacritty
    ~/.config/base16-shell: .base16-shell
    ~/.config/cava: cava
    ~/.config/espanso: espanso
    ~/.config/fish: fish
    ~/.config/gh/config.yml: github/config.yml
    ~/.config/karabiner: karabiner
    ~/.config/kitty: kitty
    ~/.config/lazydocker/config.yml: docker/lazydocker.yml
    ~/.config/lazygit/config.yml: git/lazygit.yml
    ~/.config/nvim: nvim
    ~/.config/ranger: ranger
    ~/.config/skhd: skhd
    ~/.config/starship.toml: prompt/starship.toml
    ~/.config/tmuxinator: tmuxinator
    ~/.config/yabai: yabai
    ~/.ctags: search/ctags
    ~/.curlrc: url/curlrc
    ~/.default-gems: asdf/default-gems
    ~/.default-npm-packages: asdf/default-npm-packages
    ~/.default-python-packages: asdf/default-python-packages
    ~/.editorconfig: style/editorconfig
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.gitmux.conf: tmux/gitmux.conf
    ~/.hammerspoon: hammerspoon
    ~/.pandoc: pandoc
    ~/.ripgreprc: search/ripgrep
    ~/.tmux-cht-command: tmux/tmux-cht-command
    ~/.tmux-cht-languages: tmux/tmux-cht-languages
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vale.ini: style/vale.ini
    ~/.wget: url/wget
    ~/.zsh.d: zsh/zsh.d
    ~/.zshrc: zsh/zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [
        ~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1,
        Installing tmux plugins,
      ]
