- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.ack: ack
    ~/.ag: ag
    ~/.config/alacritty: alacritty
    ~/.config/base16-shell: .base16-shell
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship.toml
    ~/.ctags: ctags
    ~/.editorconfig: editorconfig
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.hammerspoon: hammerspoon
    ~/.pandoc: pandoc
    ~/.ripgreprc: ripgrep
    ~/.wget: wget
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
