[tools]
atuin = "latest"
bat = "latest"
bat-extras = "latest"
claude = "latest"
claude-code = "latest"
codex = "latest"
delta = "latest"
docker-cli = "latest"
docker-compose = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
gitleaks = "latest"
grok = "latest"
herdr = "latest"
hunk = "latest"
hunkdiff = "latest"
jj = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyssh = "latest"
opencode = "latest"
oxlint = "latest"
pandoc = "latest"
pi = "latest"
pnpm = "latest"
postgres = "latest"
prettier = "latest"
ripgrep = "latest"
rtk = "latest"
shellcheck = "latest"
shfmt = "latest"
sqlite = "latest"
starship = "latest"
superfile = "latest"
tmux = "latest"
typst = "latest"
uv = "latest"
worktrunk = "latest"
yazi = "latest"
youtube-dl = "latest"
yq = "latest"
zoxide = "latest"
