name: Standard
root: ~/.dotfiles/
windows:
  - Vim: vim
  - Dotfiles: clear
  - Terminal: cd; clear
  - Cheatsheet: cht.sh --shell
  - Raycast: cd ~/Code/GitHub/raycast-scripts
  - Downloads: cd ~/Downloads; clear
