require("kogakure.options")
require("kogakure.keymaps")
require("kogakure.functions")
require("kogakure.autocommands")
require("kogakure.colorscheme")
require("kogakure.plugins")
require("kogakure.lsp")

require("kogakure/text-objects").basic_text_objects()
require("kogakure/text-objects").indent_text_objects()
