[privacy]
telemetry_enabled = true
crash_reporting_enabled = true
custom_secret_regex_list = [
  { name = "IPv4 Address", pattern = '\b((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}\b' },
  {
    name = "IPv6 Address",
    pattern = '\b((([0-9A-Fa-f]{1,4}:){1,6}:)|(([0-9A-Fa-f]{1,4}:){7}))([0-9A-Fa-f]{1,4})\b',
  },
  { name = "Phone Number", pattern = '\b(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\b' },
  {
    name = "MAC Address",
    pattern = '\b((([a-zA-z0-9]{2}[-:]){5}([a-zA-z0-9]{2}))|(([a-zA-z0-9]{2}:){5}([a-zA-z0-9]{2})))\b',
  },
  { name = "Google API Key", pattern = '\bAIza[0-9A-Za-z-_]{35}\b' },
  {
    name = "AWS Access ID",
    pattern = '\b(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}\b',
  },
  { name = "Slack App Token", pattern = '\bxapp-[0-9]+-[A-Za-z0-9_]+-[0-9]+-[a-f0-9]+\b' },
  { name = "GitHub Classic Personal Access Token", pattern = '\bghp_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Fine-Grained Personal Access Token", pattern = '\bgithub_pat_[A-Za-z0-9_]{82}\b' },
  { name = "GitHub OAuth Access Token", pattern = '\bgho_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub User-to-Server Token", pattern = '\bghu_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Server-to-Server Token", pattern = '\bghs_[A-Za-z0-9_]{36}\b' },
  { name = "Stripe Key", pattern = '\b(?:r|s)k_(test|live)_[0-9a-zA-Z]{24}\b' },
  { name = "Firebase Auth Domain", pattern = '\b([a-z0-9-]){1,30}(\.firebaseapp\.com)\b' },
  { name = "JWT", pattern = '\b(ey[a-zA-z0-9_\-=]{10,}\.){2}[a-zA-z0-9_\-=]{10,}\b' },
  { name = "OpenAI API Key", pattern = '\bsk-[a-zA-Z0-9]{48}\b' },
  { name = "Anthropic API Key", pattern = '\bsk-ant-api\d{0,2}-[a-zA-Z0-9\-]{80,120}\b' },
  { name = "Generic SK API Key", pattern = '\bsk-[a-zA-Z0-9\-]{10,100}\b' },
  { name = "Fireworks API Key", pattern = '\bfw_[a-zA-Z0-9]{24}\b' },
  { name = "Warp API Key", pattern = '\bwk-[0-9]+\.[A-Fa-f0-9.\-]+\b' },
]

[privacy.secret_redaction]
enabled = true

[appearance]
spacing = "normal"

[appearance.vertical_tabs]
enabled = true
display_granularity = "tabs"
view_mode = "compact"
primary_info = "command"
compact_subtitle = "branch"
tab_item_mode = "focused_session"
show_details_on_hover = true
use_latest_prompt_as_title = true
show_panel_in_restored_windows = true
hide_title_bar_search_bar = false

[appearance.themes]
theme = "dark"
system_theme = true

[appearance.window]
zoom_level = 150
override_opacity = 50
override_blur = 45

[appearance.text]
font_name = "MonaspiceNe Nerd Font Mono"
notebook_font_size = 14.0
font_size = 14.0
ligature_rendering_enabled = true

[appearance.icon]
app_icon = "default"

[appearance.tabs]
header_toolbar_chip_selection = "default"

[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]
is_any_ai_enabled = true

[agents.warp_agent.other]
show_conversation_history = false
show_agent_notifications = true
should_show_oz_updates_in_zero_state = false
should_render_use_agent_toolbar_for_user_commands = false
agent_attribution_enabled = false

[agents.warp_agent.input]
nld_in_terminal_enabled = false
ai_auto_detection_enabled = false
show_agent_tips = false

[agents.warp_agent.input.agent_toolbar_chip_selection_setting]

[agents.warp_agent.input.agent_toolbar_chip_selection_setting.custom]
left = [
  { context_chip = "username" },
  { context_chip = "ssh" },
  { context_chip = "working_directory" },
  { context_chip = "shell_git_branch" },
  { context_chip = "git_diff_stats" },
  { context_chip = "github_pull_request" },
  "nld_toggle",
]
right = [
  { context_chip = "agent_plan_and_todo_list" },
  "context_window_usage",
  "model_selector",
  "handoff_to_cloud",
  "voice_input",
  "file_attach",
]

[agents.warp_agent.active_ai]
enabled = false

[agents.third_party]
should_render_cli_agent_toolbar = true
auto_open_composer_on_cli_agent_start = false

[agents.voice]
voice_input_toggle_key = "fn"

[warp_drive]
enabled = true

[general]
default_session_mode = "terminal"
login_item = false
show_warning_before_quitting = false

[code]

[code.editor]
show_code_review_button = true
show_global_search = true
show_project_explorer = true
open_file_editor = "env_editor"
auto_open_code_review_pane_on_first_agent_change = true
open_code_panels_file_editor = "warp"
open_file_layout = "new_tab"

[code.indexing]
agent_mode_codebase_context_auto_indexing = false

[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[text_editing]
vim_mode_enabled = true
vim_unnamed_system_clipboard = true

[account]
is_settings_sync_enabled = true

[terminal]
osc52_clipboard_access = "read_write"
use_audible_bell = true
show_terminal_zero_state_block = false

[terminal.input]
input_box_type_setting = "classic"
honor_ps1 = true
show_hint_text = false
