[log]
enabled = false

[manager]
ratio = [1, 4, 3]
show_hidden = false
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[[opener.edit]]
block = true
run = "nvim \"$@\""
