-- Package manager for LSP servers, DAP servers, linters, and formatters
-- https://github.com/williamboman/mason.nvim
return {
	"williamboman/mason.nvim",
	opts = {
		ensure_installed = {
			"astro-language-server",
			"black",
			"codespell",
			"cspell",
			"css-lsp",
			"cssmodules-language-server",
			"delve",
			"deno",
			"diagnostic-languageserver",
			"emmet-ls",
			"eslint-lsp",
			"eslint_d",
			"gofumpt",
			"goimports",
			"gomodifytags",
			"html-lsp",
			"htmlbeautifier",
			"impl",
			"isort",
			"json-lsp",
			"lua-language-server",
			"markdown-oxide",
			"nixpkgs-fmt",
			"prettier",
			"prettierd",
			"pyright",
			"rubocop",
			"rubyfmt",
			"shellcheck",
			"stylua",
			"svelte-language-server",
			"tailwindcss-language-server",
			"typescript-language-server",
			-- "typos-lsp",
			"vale",
			"yaml-language-server",
			"yamlfmt",
		},
		ui = {
			border = "rounded",
			icons = {
				package_installed = "✓",
				package_pending = "➜",
				package_uninstalled = "✗",
			},
		},
	},
}
