agent_notes = true
exclude_untracked = true
line_numbers = true
menu_bar = true
mode = "auto" # auto, split, stack
theme = "catppuccin-mocha"
transparent_background = true
vcs = "git" # git, jj, sl
watch = false
wrap_lines = true
