git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never syntax-theme=Dracula
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "W"
    command: git commit --no-verify
    context: "global"
    output: terminal
