#!/bin/sh

#####################################
### Visual Studio Code Extensions ###
#####################################

# code --list extensions

code --install-extension ChakrounAnas.turbo-console-log
code --install-extension Codeium.codeium
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-labs
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension Gruntfuggly.todo-tree
code --install-extension JuanBlanco.solidity
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension PKief.material-icon-theme
code --install-extension Perkovec.emoji
code --install-extension Prisma.prisma
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension XadillaX.viml
code --install-extension YuTengjing.open-in-external-app
code --install-extension adamvoss.vscode-languagetool
code --install-extension akamud.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension anteprimorac.html-end-tag-labels
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension astro-build.astro-vscode
code --install-extension asvetliakov.snapshot-tools
code --install-extension asvetliakov.vscode-neovim
code --install-extension azemoh.one-monokai
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension codezombiech.gitignore
code --install-extension csstools.postcss
code --install-extension davidlday.languagetool-linter
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension dendron.dendron
code --install-extension dendron.dendron-paste-image
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension enkia.tokyo-night
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension errata-ai.vale-server
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension foam.foam-vscode
code --install-extension gerane.Theme-TomorrowNight
code --install-extension ginfuru.better-nunjucks
code --install-extension idleberg.applescript
code --install-extension jasonnutter.search-node-modules
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kaleidoscope-app.vscode-ksdiff
code --install-extension kamikillerto.vscode-colorize
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liviuschera.noctis
code --install-extension mattpocock.ts-error-translator
code --install-extension mechatroner.rainbow-csv
code --install-extension mehullakhanpal.file-ops
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-playwright.playwright
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension pnp.polacode
code --install-extension pomdtr.excalidraw-editor
code --install-extension quick-lint.quick-lint-js
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sdras.night-owl
code --install-extension silvenon.mdx
code --install-extension sleistner.vscode-fileutils
code --install-extension softwaredotcom.swdc-vscode
code --install-extension stuartzhang.stylelint-stzhang
code --install-extension styled-components.vscode-styled-components
code --install-extension stylelint.vscode-stylelint
code --install-extension svanimpe.stencil
code --install-extension svelte.svelte-vscode
code --install-extension tchayen.markdown-links
code --install-extension thenikso.github-plus-theme
code --install-extension unifiedjs.vscode-mdx
code --install-extension vivaxy.vscode-conventional-commits
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xyc.vscode-mdx-preview
code --install-extension yinfei.luahelper
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension znck.grammarly
