#!/bin/sh

#####################################
### Visual Studio Code Extensions ###
#####################################

code --install-extension akamud.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension anteprimorac.html-end-tag-labels
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension asvetliakov.snapshot-tools
code --install-extension asvetliakov.vscode-neovim
code --install-extension azemoh.one-monokai
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension csstools.postcss
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension foam.foam-vscode
code --install-extension gamunu.vscode-yarn
code --install-extension gerane.Theme-TomorrowNight
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golf1052.base16-generator
code --install-extension Gruntfuggly.todo-tree
code --install-extension jasonnutter.search-node-modules
code --install-extension jcbuisson.vue
code --install-extension johnpapa.winteriscoming
code --install-extension JounQin.vscode-mdx
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension JuanBlanco.solidity
code --install-extension kamikillerto.vscode-colorize
code --install-extension KnisterPeter.vscode-github
code --install-extension kortina.vscode-markdown-notes
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension liviuschera.noctis
code --install-extension luwenjiechn.nunjucks-vscode-snippets
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension MS-CEINTL.vscode-language-pack-de
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension patbenatar.advanced-new-file
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ronnidc.nunjucks
code --install-extension sallar.vscode-duotone-dark
code --install-extension sdras.night-owl
code --install-extension silvenon.mdx
code --install-extension sissel.shopify-liquid
code --install-extension softwaredotcom.swdc-vscode
code --install-extension stuartzhang.stylelint-stzhang
code --install-extension svanimpe.stencil
code --install-extension svelte.svelte-vscode
code --install-extension tchayen.markdown-links
code --install-extension thenikso.github-plus-theme
code --install-extension Tyriar.sort-lines
code --install-extension vadistic.mdx-inline
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension XadillaX.viml
code --install-extension xyc.vscode-mdx-preview
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension znck.grammarly
