default_startup_script = "~/.config/sesh/scripts/open_files"

[[startup_scripts]]
session_path = "~/Code/personal/websites/stefanimhoff-de"
script_path = "~/.config/sesh/scripts/node_dev"

[[session]]
name = " Dotfiles"
path = "~/.dotfiles"

[[session]]
name = " Downloads"
path = "~/Downloads"
startup_command = "la"

[[session]]
name = "󰪶 Zettelkasten"
path = "~/Code/personal/obsidian/zettelkasten/"

[[session]]
name = " Highlights"
path = "~/Code/personal/obsidian/highlights/"

[[session]]
name = " stefanimhoff-de"
path = "~/Code/personal/websites/stefanimhoff-de/"

[[session]]
name = "󰝴 kogakure-de"
path = "~/Code/personal/websites/kogakure-de/"

[[session]]
name = " hamburg-stefanimhoff-de"
path = "~/Code/personal/websites/hamburg-stefanimhoff-de/"

[[session]]
name = "󱓟 Skills"
path = "~/Code/personal/skills"
