config:
  fallback-icon: "?"
  show-name: true

icons:
  bat: "󰭟"
  claude: "󰚩"
  gh: ""
  nix-env: "󱄅"
  nix-shell: "󱄅"
  nix: "󱄅"
  nvim: ""
  ollama: "󰚩"
  opencode: "󰚩"
  pnpm: ""
  reattach-to-user-namespace: ""
  spf: "󰪶"
  sudo: "🔒"
