[tools]
bun = "latest"
deno = "latest"
direnv = "latest"
go = "latest"
lua = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
not_found_auto_install = true
