[tools]
bun = "latest"
deno = "2.0.0"
direnv = "2.32.2"
go = "1.22.5"
lua = "5.4.6"
neovim = "0.11.1"
node = "22.17.1"
python = "3.10.9"
ruby = "3.4.2"
rust = "1.88.0"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
not_found_auto_install = true
