[tools]
bun = "latest"
deno = "2.4.3"
direnv = "2.37.1"
go = "1.24.5"
lua = "5.4.8"
neovim = "0.11.3"
node = "22.17.1"
python = "3.13.5"
ruby = "3.4.2"
rust = "nightly"
usage = "2.2.2"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
not_found_auto_install = true
