[tools]
bun = "latest"
deno = "latest"
direnv = "latest"
go = "latest"
lua = "latest"
neovim = "latest"
node = "22.15.1"
"npm:playwright-cli" = "latest"
python = "latest"
ruby = "3.4.2"
rust = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
not_found_auto_install = true
